steps:
  # Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/calculator:$COMMIT_SHA", "."]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/calculator:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/calculator-deployment",
        "calculator=gcr.io/sit323-23t1-kingsbury-37a7a8c/calculator:$COMMIT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-west1"
      - "CLOUDSDK_CONTAINER_CLUSTER=calculator-cluster"
