apiVersion: apps/v1
kind: Deployment
metadata:
  name: hd_calculator-deployment
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: calculator-container
          image: gcr.io/sit323-23t1-kingsbury-37a7a8c/calculator:latest
          ports:
            - containerPort: 8080
